[paths]
UPLOAD_FOLDER = "uploads"
top_wear_csv = "data/top_wear_clothing_attributes.csv"
bottom_wear_csv = "data/bottom_wear_clothing_attributes.csv"
clustering_weather_data_topwear="data/clustering_weather_data_topwear.csv"
users_csv = "data/users.csv"
weather_suitability_model = "Models/weather_classification/weather_classifier_model.pkl"


#api_key="AIzaSyA18ja6FDxSA6g9-XVuxszsb5wR7eNOx2Q"

[geminiai]
api_key="AIzaSyCslb1IFhdn11AoFlFLtHIkDzARRBV0Jqs"
model="gemini-1.5-pro-latest"

[attribute_models]
model_path = "Models/attribute_models"

[LLMmodel]
model="llama3.2:1b"

[session_management_key]
secret_key = "0236182485f3cc06f485de4d5156a91c0aa15222c8530ff3d11096681344c4de"